import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const srcDir = join(import.meta.dirname, '..', 'src');
const index = readFileSync(join(srcDir, 'pages', 'Index.tsx'), 'utf8');
const layout = readFileSync(join(srcDir, 'pages', 'Layout.tsx'), 'utf8');
const app = readFileSync(join(srcDir, 'App.tsx'), 'utf8');
const adminMenu = readFileSync(join(srcDir, 'pages', 'admin', 'adminMenu.tsx'), 'utf8');
const css = readFileSync(join(srcDir, 'index.css'), 'utf8');
const websiteMonitorEvents = readFileSync(join(srcDir, 'utils', 'websiteMonitorEvents.ts'), 'utf8');

test('public website monitor view uses nav switch, simple Kuma-style list, and safe links', () => {
  const list = readFileSync(join(srcDir, 'components', 'WebsiteMonitorList.tsx'), 'utf8');
  const heartbeat = readFileSync(join(srcDir, 'components', 'WebsiteHeartbeatBar.tsx'), 'utf8');

  assert.match(layout, /nav-monitor-switch/);
  assert.match(layout, /size="2"/);
  assert.match(layout, /SegmentedControl\.Item value="servers"/);
  assert.match(layout, /SegmentedControl\.Item value="websites"/);
  assert.match(index, /new URLSearchParams\(location\.search\)/);
  assert.match(index, /monitorMode === 'servers' &&/);
  assert.match(index, /const NodeCard = React\.lazy\(\(\) => import\('\.\.\/components\/NodeCard'\)\)/);
  assert.match(index, /const NodeDisplay = React\.lazy\(\(\) => import\('\.\.\/components\/NodeDisplay'\)\)/);
  assert.doesNotMatch(index, /import NodeCard from '\.\.\/components\/NodeCard'/);
  assert.doesNotMatch(index, /import NodeDisplay from '\.\.\/components\/NodeDisplay'/);
  assert.doesNotMatch(index, /if \(monitorMode === 'servers' && clientsLoading\) return <Loading \/>/);
  assert.doesNotMatch(index, /loading\s*\|\|\s*clientsLoading/);
  assert.doesNotMatch(index, /import Loading from '\.\.\/components\/Loading'/);
  assert.match(index, /WEBSITE_MONITOR_REFRESH_MS = 120_000/);
  assert.match(index, /WEBSITE_MONITOR_PERIODS = \[/);
  assert.match(index, /const \[websitePeriodHours, setWebsitePeriodHours\] = useState\(24\)/);
  assert.match(index, /<WebsiteMonitorList monitors=\{websites\} loading=\{websitesLoading\} periodHours=\{websitePeriodHours\} onPeriodChange=\{setWebsitePeriodHours\}/);
  assert.doesNotMatch(index, /WEBSITE_MONITOR_CACHE_KEY = 'cf_monitor_public_websites'/);
  assert.doesNotMatch(index, /useState<WebsiteMonitorSummary\[\]>\(getCachedWebsites\)/);
  assert.match(index, /const \[websites, setWebsites\] = useState<WebsiteMonitorSummary\[\]>\(\[\]\)/);
  assert.match(index, /const \[websitesLoading, setWebsitesLoading\] = useState\(monitorMode === 'websites' && websites\.length === 0\)/);
  assert.match(index, /const list = normalizeWebsiteSummaries\(data\)/);
  assert.match(index, /setWebsitesLoading\(true\)/);
  assert.match(index, /setWebsitesLoading\(false\)/);
  assert.match(index, /monitorMode !== 'servers'/);
  assert.match(index, /monitorMode !== 'websites'/);
  assert.match(index, /const url = `\/api\/websites\?hours=\$\{websitePeriodHours\}\$\{fresh \? `&_fresh=\$\{Date\.now\(\)\}` : ''\}`/);
  assert.match(index, /fetchWithBootstrapRetry\(url, fresh \? \{ cache: 'reload' \} : undefined\)/);
  assert.match(index, /function applyWebsiteMonitorUpdate/);
  assert.match(index, /subscribeWebsiteMonitorsUpdated\(\(detail\) => \{/);
  assert.match(index, /if \(!detail \|\| detail === true\) \{[\s\S]{0,80}loadWebsites\(true\)/);
  assert.match(index, /setWebsites\(\(current\) => \{/);
  assert.match(index, /current\.length > 0 && list\.length === 0 \? current : list/);
  assert.match(index, /loadWebsites\(true\);\s*const unsubscribe/);
  assert.match(index, /setInterval\(loadWhenVisible, WEBSITE_MONITOR_REFRESH_MS\)/);
  assert.match(index, /\}, \[monitorMode, websitePeriodHours\]\)/);
  assert.match(index, /<WebsiteMonitorList monitors=\{websites\} loading=\{websitesLoading\}/);
  assert.doesNotMatch(index, /<WebsiteMonitorDetails/);
  assert.match(list, /className="kuma-monitor-list"/);
  assert.match(list, /loading,[\s\S]*periodHours,[\s\S]*onPeriodChange,[\s\S]*}: \{\s*monitors: WebsiteMonitorSummary\[\];\s*loading\?: boolean;\s*periodHours: number;\s*onPeriodChange: \(hours: number\) => void;/);
  assert.match(list, /summary\.total === 0 \? \(loading \? '加载中' : '暂无网站'\)/);
  assert.match(list, /monitors\.length === 0 && !loading/);
  assert.match(list, /className="kuma-monitor-summary"/);
  assert.match(list, /className="kuma-monitor-title-line"/);
  assert.match(list, /<Text size="4" weight="bold">网站监控<\/Text>[\s\S]{0,220}\$\{summary\.up\} 正常 \/ \$\{summary\.down\} 失效 \/ \$\{summary\.total\} 总数/);
  assert.match(list, /periodHours,\s*onPeriodChange/);
  assert.match(index, /interval_sec: typeof value\.interval_sec === 'number' \? value\.interval_sec : 120/);
  assert.match(list, /interval_sec: number;/);
  assert.match(list, /const DEFAULT_WEBSITE_INTERVAL_SEC = 120/);
  assert.match(list, /function heartbeatSegmentCount\(periodHours: number, intervalSec = DEFAULT_WEBSITE_INTERVAL_SEC\)/);
  assert.match(list, /if \(periodHours === 1\) return Math\.max\(1, Math\.ceil\(periodHours \* 60 \* 60 \/ interval\)\)/);
  assert.match(list, /return 72/);
  assert.match(list, /function bucketChecksByPeriod/);
  assert.match(list, /const bucketMs = periodHours \* 60 \* 60 \* 1000 \/ segmentCount/);
  assert.match(list, /const segmentCount = heartbeatSegmentCount\(periodHours, monitor\.interval_sec\)/);
  assert.match(list, /const bucketedChecks = bucketChecksByPeriod\(monitor\.checks \|\| \[\], periodHours, segmentCount\)/);
  assert.match(list, /<WebsiteHeartbeatBar checks=\{bucketedChecks\} max=\{segmentCount\} \/>/);
  assert.match(list, /\{periodHours\}h/);
  assert.match(list, /periods = \[1, 24, 72\]/);
  assert.match(list, /\{hours\}小时/);
  assert.match(list, /target="_blank"/);
  assert.match(list, /rel="noopener noreferrer"/);
  assert.match(list, /event\.stopPropagation\(\)/);
  assert.match(list, /function statusLine\(monitor: WebsiteMonitorSummary\)/);
  assert.match(list, /monitor\.status === 'down'[\s\S]{0,120}HTTP/);
  assert.doesNotMatch(list, /<Text[\s\S]{0,260}\{statusText\(monitor\.status\)\} · HTTP/);
  assert.match(heartbeat, /className=\{`website-heartbeat-bar/);
  assert.match(heartbeat, /--heartbeat-segment-count/);
  assert.match(heartbeat, /function heartbeatResultText\(check: WebsiteHeartbeatPoint\)/);
  assert.match(heartbeat, /useLayoutEffect/);
  assert.match(heartbeat, /window\.innerWidth - margin - halfWidth/);
  assert.match(heartbeat, /className="website-heartbeat-tooltip"/);
  assert.match(heartbeat, /--heartbeat-tooltip-arrow-left/);
  assert.match(heartbeat, /data-tooltip=\{bar\.interactive \? bar\.title : undefined\}/);
  assert.match(heartbeat, /onMouseEnter=\{bar\.interactive \? \(event\) => showTooltip/);
  assert.match(heartbeat, /onClick=\{bar\.interactive \? \(event\) => showTooltip/);
  assert.match(heartbeat, /tabIndex=\{bar\.interactive \? 0 : undefined\}/);
  assert.doesNotMatch(heartbeat, /title=\{bar\.title\}/);
});

test('admin website management route and menu are wired beside server management', () => {
  const websites = readFileSync(join(srcDir, 'pages', 'admin', 'Websites.tsx'), 'utf8');

  assert.match(app, /const AdminWebsites = lazy\(\(\) => import\('\.\/pages\/admin\/Websites'\)\)/);
  assert.match(app, /function PublicIndexRoute\(\)/);
  assert.match(app, /return <Index \/>/);
  assert.doesNotMatch(app, /enabled=\{serverView\} viewer=\{serverView\}/);
  assert.match(app, /<Route index element=\{<LiveDataRoute><PublicIndexRoute \/><\/LiveDataRoute>\}/);
  assert.match(app, /<Route path="websites" element=\{<AdminWebsites \/>\}/);
  assert.match(adminMenu, /\{ path: '\/admin\/websites', label: '网站'/);
  assert.match(adminMenu, /pathname\.startsWith\('\/admin\/websites'\)/);
  assert.match(websites, /apiFetch\(refresh \? '\/admin\/websites\?refresh=1' : '\/admin\/websites'\)/);
  assert.match(websites, /function applyWebsiteMonitorUpdate/);
  assert.match(websites, /subscribeWebsiteMonitorsUpdated\(\(detail\) => \{/);
  assert.match(websites, /apiFetch\('\/admin\/websites\/add'/);
  assert.match(websites, /apiFetch\('\/admin\/websites\/visibility'/);
  assert.match(websites, /apiFetch\('\/admin\/websites\/enabled'/);
  assert.match(websites, /apiFetch\('\/admin\/websites\/delete'/);
  assert.match(websites, /apiFetch\(`\/admin\/websites\/\$\{monitor\.id\}\/check`/);
  assert.match(websites, /interval_sec:\s*120/);
  assert.match(websites, /notifyWebsiteMonitorsUpdated\(savedMonitor \? \{ upsert: \[savedMonitor\] \} : true\)/);
  assert.match(websites, /notifyWebsiteMonitorsUpdated\(\{ remove: \[monitor\.id\] \}\)/);
  assert.match(websites, /对非管理员隐藏/);
  assert.match(websites, /Dialog\.Root/);
  assert.match(websites, /Table\.Root/);
  assert.match(websites, /DndContext/);
  assert.match(websites, /SortableWebsiteRow/);
  assert.match(websites, /GripVertical/);
  assert.match(websites, /Checkbox/);
  assert.match(websites, /arrayMove/);
  assert.match(websites, /const DEFAULT_EXPECTED_STATUS_MIN = 200/);
  assert.match(websites, /const DEFAULT_EXPECTED_STATUS_MAX = 399/);
  assert.match(websites, /type WebsiteMethod = 'GET' \| 'HEAD' \| 'TCP'/);
  assert.match(websites, /monitor\.status === 'up' \? 'TCP 可达' : effectiveReasonLabel\(monitor\.last_effective_reason\)/);
  assert.match(websites, /检测方式/);
  assert.match(websites, /Select\.Item value="TCP"/);
  assert.match(websites, /form\.method !== 'TCP'[\s\S]*最小状态码/);
  assert.match(websites, /form\.method === 'TCP'[\s\S]*主机或 IP/);
  assert.match(websites, /onRemove: \(monitor: WebsiteMonitor\) => void/);
  assert.match(websites, /onClick=\{\(\) => onRemove\(monitor\)\}[\s\S]{0,120}<Trash2 size=\{13\} \/>删除/);
  assert.doesNotMatch(websites, /Dialog\.Title>\{editMonitor \? '编辑网站' : '添加网站'\}[\s\S]*<Trash2 size=\{16\} \/> 删除[\s\S]*<\/Dialog\.Content>/);
  assert.match(websites, /admin-node-card-panel/);
  assert.match(websites, /admin-status-filter/);
  assert.match(websites, /admin-filter-spacer/);
  assert.match(websites, /admin-sort-controls/);
  assert.match(websites, /admin-node-card-panel-header/);
});

test('website monitor changes notify public views without adding dependencies', () => {
  assert.match(websiteMonitorEvents, /WEBSITE_MONITORS_UPDATED_EVENT/);
  assert.match(websiteMonitorEvents, /type WebsiteMonitorsUpdateDetail/);
  assert.match(websiteMonitorEvents, /window\.dispatchEvent\(new CustomEvent\(WEBSITE_MONITORS_UPDATED_EVENT, \{ detail \}\)\)/);
  assert.match(websiteMonitorEvents, /localStorage\.setItem\(WEBSITE_MONITORS_UPDATED_EVENT/);
  assert.match(websiteMonitorEvents, /JSON\.stringify\(\{ at: Date\.now\(\), detail \}\)/);
  assert.match(websiteMonitorEvents, /new BroadcastChannel\(CHANNEL_NAME\)/);
  assert.match(websiteMonitorEvents, /callback\(parsed\?\.detail\)/);
  assert.match(websiteMonitorEvents, /window\.addEventListener\('storage', onStorage\)/);
});

test('admin settings pages share prefetched settings for smooth tab switches', () => {
  const settingsLayout = readFileSync(join(srcDir, 'pages', 'admin', 'SettingsLayout.tsx'), 'utf8');
  const settingsSite = readFileSync(join(srcDir, 'pages', 'admin', 'SettingsSite.tsx'), 'utf8');
  const settingsGeneral = readFileSync(join(srcDir, 'pages', 'admin', 'SettingsGeneral.tsx'), 'utf8');
  const adminLayout = readFileSync(join(srcDir, 'pages', 'admin', 'AdminLayout.tsx'), 'utf8');

  assert.match(settingsLayout, /loadSettingsScope\('site'\)/);
  assert.match(settingsLayout, /loadSettingsScope\('general'\)/);
  assert.match(settingsLayout, /settingsCache/);
  assert.match(settingsSite, /loadSettingsScope\('site'\)/);
  assert.match(settingsGeneral, /loadSettingsScope\('general'\)/);
  assert.doesNotMatch(settingsSite, /apiFetch\('\/admin\/settings\?scope=site'\)[\s\S]{0,220}\.finally\(\(\) => setLoading\(false\)\)/);
  assert.doesNotMatch(settingsGeneral, /Promise\.all\(\[[\s\S]{0,220}apiFetch\('\/admin\/capacity'\)[\s\S]{0,220}\.finally\(\(\) => setLoading\(false\)\)/);
  assert.match(adminLayout, /import\("\.\/SettingsLayout"\)/);
  assert.match(adminLayout, /import\("\.\/SettingsSite"\)/);
  assert.match(adminLayout, /import\("\.\/SettingsGeneral"\)/);
});

test('website monitor layouts expose stable responsive class hooks', () => {
  assert.match(css, /\.nav-monitor-switch[\s\S]{0,160}left:\s*50%/);
  assert.match(css, /\.nav-monitor-switch[\s\S]{0,220}min-height:\s*36px/);
  assert.match(css, /\.nav-monitor-switch button[\s\S]{0,120}min-height:\s*30px/);
  assert.match(layout, /Powered by CF VPS Monitor\./);
  assert.match(css, /\.footer\s*\{[\s\S]{0,160}padding:\s*8px var\(--layout-padding\)/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.nav-monitor-switch\s*\{[\s\S]{0,120}transform:\s*translate\(-50%, 0\) scale\(0\.86\)/);
  assert.match(css, /\.website-monitor-shell/);
  assert.match(css, /\.kuma-monitor-list/);
  assert.match(css, /\.kuma-monitor-summary/);
  assert.match(css, /\.kuma-monitor-title-line/);
  assert.match(css, /\.kuma-monitor-uptime-pill/);
  assert.match(css, /\.admin-dashboard-page,\s*[\r\n]+\.admin-websites-page[\s\S]{0,100}gap:\s*8px/);
  assert.match(css, /\.admin-website-overview-hero \.admin-overview-item[\s\S]{0,120}min-width:\s*108px/);
  assert.match(css, /\.admin-filter-spacer[\s\S]{0,120}visibility:\s*hidden/);
  assert.match(css, /\.kuma-monitor-row[\s\S]{0,160}grid-template-columns:\s*58px minmax\(128px, 300px\) minmax\(520px, 1fr\)/);
  assert.match(css, /\.website-heartbeat-segment\.is-interactive[\s\S]{0,80}cursor:\s*pointer/);
  assert.match(css, /\.website-heartbeat-segment\.is-interactive:hover,[\s\S]{0,180}transform:\s*scale\(1\.5\)/);
  assert.match(css, /\.website-heartbeat-tooltip[\s\S]{0,120}position:\s*fixed/);
  assert.match(css, /\.website-heartbeat-tooltip[\s\S]{0,180}max-width:\s*min\(260px, calc\(100vw - 16px\)\)/);
  assert.match(css, /\.website-heartbeat-tooltip-arrow[\s\S]{0,120}var\(--heartbeat-tooltip-arrow-left/);
  assert.doesNotMatch(css, /\.website-heartbeat-segment\.is-interactive:hover::after/);
  assert.doesNotMatch(css, /content:\s*attr\(data-tooltip\)/);
  assert.doesNotMatch(css, /\.website-heartbeat-bar:hover \.website-heartbeat-segment[\s\S]{0,120}transform/);
  assert.match(css, /\.admin-website-control-cell[\s\S]{0,120}min-width:\s*66px/);
  assert.match(css, /\.admin-website-row-controls[\s\S]{0,120}flex-wrap:\s*nowrap/);
  assert.match(css, /\.admin-website-name-cell/);
  assert.match(css, /\.admin-website-url-cell/);
  assert.match(css, /\.admin-website-actions-cell[\s\S]{0,120}min-width:\s*294px/);
  assert.match(css, /\.admin-website-name-text[\s\S]{0,180}text-overflow:\s*ellipsis/);
  assert.match(css, /@media \(max-width: 768px\)[\s\S]*\.admin-websites-page \.admin-search-cluster\s*\{[\s\S]{0,120}margin-left:\s*auto/);
  assert.match(css, /repeat\(var\(--heartbeat-segment-count, 60\), minmax\(3px, 1fr\)\)/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.website-monitor-shell/);
  assert.doesNotMatch(css, /website-monitor-shell[\s\S]{0,120}border-radius:\s*(1[2-9]|[2-9]\d)px/);
});
