begin;

set local search_path = public;

create table if not exists clients (
  uuid text primary key,
  token text unique,
  token_hash text unique,
  token_last_used_at timestamptz,
  token_last_used_ip text,
  token_rotated_at timestamptz,
  name text not null default '',
  cpu_name text not null default '',
  virtualization text not null default '',
  arch text not null default '',
  cpu_cores integer not null default 0,
  os text not null default '',
  kernel_version text not null default '',
  gpu_name text not null default '',
  ipv4 text not null default '',
  ipv6 text not null default '',
  region text not null default '',
  remark text not null default '',
  public_remark text not null default '',
  mem_total bigint not null default 0,
  swap_total bigint not null default 0,
  disk_total bigint not null default 0,
  version text not null default '',
  price double precision not null default 0,
  billing_cycle smallint not null default 0,
  auto_renewal smallint not null default 0,
  currency text not null default '$',
  expired_at timestamptz,
  "group" text not null default '',
  tags text not null default '',
  hidden smallint not null default 0,
  traffic_limit bigint not null default 0,
  traffic_limit_type text not null default 'max',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_clients_sort_order on clients(sort_order, name);

create table if not exists records (
  id bigint generated by default as identity primary key,
  client text not null,
  time timestamptz not null,
  cpu double precision not null default 0,
  gpu double precision not null default 0,
  ram bigint not null default 0,
  ram_total bigint not null default 0,
  swap bigint not null default 0,
  swap_total bigint not null default 0,
  load double precision not null default 0,
  temp double precision not null default 0,
  disk bigint not null default 0,
  disk_total bigint not null default 0,
  net_in bigint not null default 0,
  net_out bigint not null default 0,
  net_total_up bigint not null default 0,
  net_total_down bigint not null default 0,
  process_count integer not null default 0,
  connections integer not null default 0,
  connections_udp integer not null default 0,
  uptime bigint not null default 0,
  constraint records_client_fkey foreign key (client) references clients(uuid) deferrable initially deferred
);

create index if not exists idx_records_client_time on records(client, time);
create index if not exists idx_records_time on records(time);

create table if not exists gpu_records (
  id bigint generated by default as identity primary key,
  client text not null,
  time timestamptz not null,
  device_index integer not null default 0,
  device_name text not null default '',
  mem_total bigint not null default 0,
  mem_used bigint not null default 0,
  utilization double precision not null default 0,
  temperature integer not null default 0,
  constraint gpu_records_client_fkey foreign key (client) references clients(uuid) deferrable initially deferred
);

create index if not exists idx_gpu_records_client_time on gpu_records(client, time);
create index if not exists idx_gpu_records_time on gpu_records(time);

create table if not exists gpu_snapshots (
  id bigint generated by default as identity primary key,
  client text not null,
  time timestamptz not null,
  devices_json jsonb not null default '[]'::jsonb,
  constraint gpu_snapshots_client_fkey foreign key (client) references clients(uuid) deferrable initially deferred
);

create index if not exists idx_gpu_snapshots_client_time on gpu_snapshots(client, time);
create index if not exists idx_gpu_snapshots_time on gpu_snapshots(time);

create table if not exists users (
  uuid text primary key,
  username text not null unique,
  passwd text not null,
  session_version integer not null default 1,
  password_changed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists login_rate_limits (
  bucket text primary key,
  failures integer not null default 0,
  first_failed_at timestamptz not null,
  last_failed_at timestamptz not null,
  locked_until timestamptz
);

create index if not exists idx_login_rate_limits_last_failed on login_rate_limits(last_failed_at);

create table if not exists settings (
  key text primary key,
  value text not null default ''
);

create table if not exists themes (
  short text primary key,
  name text not null,
  description text not null default '',
  version text not null default '',
  author text not null default '',
  url text not null default '',
  preview_path text not null default '',
  style_path text not null,
  manifest_json text not null,
  config_json text not null default '{}',
  custom_css text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint themes_short_check check (short ~ '^[A-Za-z0-9_-]+$' and short <> 'default')
);

create table if not exists theme_assets (
  theme_short text not null,
  path text not null,
  content_type text not null,
  content_base64 text not null,
  size_bytes integer not null,
  created_at timestamptz not null default now(),
  constraint theme_assets_theme_short_fkey foreign key (theme_short) references themes(short) on delete cascade,
  primary key (theme_short, path)
);

create table if not exists ping_tasks (
  id bigint generated by default as identity primary key,
  name text not null,
  clients jsonb not null default '[]'::jsonb,
  all_clients smallint not null default 0,
  type text not null default 'icmp',
  target text not null,
  interval_sec integer not null default 60,
  sort_order integer not null default 0
);

create index if not exists idx_ping_tasks_sort_order on ping_tasks(sort_order, id);

create table if not exists ping_records (
  id bigint generated by default as identity primary key,
  client text not null,
  task_id bigint not null,
  time timestamptz not null,
  value integer not null,
  constraint ping_records_client_fkey foreign key (client) references clients(uuid) deferrable initially deferred,
  constraint ping_records_task_fkey foreign key (task_id) references ping_tasks(id) on delete cascade deferrable initially deferred
);

create index if not exists idx_ping_records_client_task_time on ping_records(client, task_id, time);
create index if not exists idx_ping_records_time on ping_records(time);

create table if not exists ping_snapshots (
  id bigint generated by default as identity primary key,
  client text not null,
  time timestamptz not null,
  values_json jsonb not null default '[]'::jsonb,
  constraint ping_snapshots_client_fkey foreign key (client) references clients(uuid) deferrable initially deferred
);

create index if not exists idx_ping_snapshots_client_time on ping_snapshots(client, time);
create index if not exists idx_ping_snapshots_time on ping_snapshots(time);

create table if not exists website_monitors (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  method text not null default 'GET',
  expected_status_min integer not null default 200,
  expected_status_max integer not null default 399,
  interval_sec integer not null default 120,
  timeout_sec integer not null default 10,
  grace_period_sec integer not null default 180,
  enabled boolean not null default true,
  hidden boolean not null default false,
  sort_order integer not null default 0,
  status text not null default 'pending',
  last_checked_at timestamptz,
  last_success_at timestamptz,
  last_failure_at timestamptz,
  last_status_code integer,
  last_raw_status_code integer,
  last_latency_ms integer,
  last_effective_reason text,
  last_error text,
  down_since timestamptz,
  last_notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint website_monitors_method_check check (method in ('GET', 'HEAD', 'TCP')),
  constraint website_monitors_status_check check (status in ('pending', 'up', 'down', 'paused')),
  constraint website_monitors_expected_status_check check (
    expected_status_min between 100 and 599
    and expected_status_max between 100 and 599
    and expected_status_min <= expected_status_max
  ),
  constraint website_monitors_interval_check check (interval_sec between 60 and 86400),
  constraint website_monitors_timeout_check check (timeout_sec between 1 and 30 and timeout_sec <= interval_sec),
  constraint website_monitors_grace_check check (grace_period_sec between 30 and 86400)
);

create table if not exists website_checks (
  id bigint generated by default as identity primary key,
  monitor_id bigint not null,
  checked_at timestamptz not null,
  ok boolean not null,
  effective_status text not null default 'down',
  effective_reason text,
  status_code integer,
  raw_status_code integer,
  latency_ms integer,
  error text,
  constraint website_checks_monitor_id_fkey foreign key (monitor_id) references website_monitors(id) on delete cascade
);

create index if not exists idx_website_monitors_sort_order on website_monitors(sort_order, id);
create index if not exists idx_website_monitors_due on website_monitors(enabled, last_checked_at, interval_sec);
create index if not exists idx_website_checks_monitor_time on website_checks(monitor_id, checked_at desc);

create table if not exists offline_notifications (
  client text primary key references clients(uuid) on delete cascade,
  enable smallint not null default 0,
  grace_period integer not null default 180,
  last_notified timestamptz
);

create table if not exists expiry_notifications (
  client text primary key references clients(uuid) on delete cascade,
  enable smallint not null default 0,
  advance_days integer not null default 7,
  last_notified timestamptz
);

create table if not exists load_notifications (
  id bigint generated by default as identity primary key,
  name text not null default '',
  clients jsonb not null default '[]'::jsonb,
  metric text not null default 'cpu',
  threshold double precision not null default 80,
  ratio double precision not null default 0.8,
  interval_min integer not null default 15,
  last_notified timestamptz
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  time timestamptz not null default now(),
  "user" text not null default '',
  action text not null default '',
  detail text not null default '',
  level text not null default 'info'
);

create index if not exists idx_audit_logs_time on audit_logs(time);

alter table users add column if not exists session_version integer not null default 1;
alter table users add column if not exists password_changed_at timestamptz;
alter table ping_tasks add column if not exists sort_order integer not null default 0;
alter table clients add column if not exists sort_order integer not null default 0;

update ping_tasks set sort_order = id where sort_order is null or sort_order = 0;

with ranked as (
  select uuid, row_number() over (order by created_at nulls last, name, uuid) as row_number
  from clients
  where sort_order is null or sort_order = 0
)
update clients
set sort_order = ranked.row_number
from ranked
where clients.uuid = ranked.uuid;

delete from settings
where key in (
  'allow_cors',
  'private_site',
  'private_site_password',
  'tempory_share_token',
  'tempory_share_token_expire_at',
  'temporary_share_token',
  'temporary_share_token_expire_at',
  'custom_head',
  'custom_body',
  'custom_footer_html',
  'agent_auto_discovery_key'
);

insert into settings (key, value) values
  ('site_title', 'CF Monitor'),
  ('site_description', '服务器监控探针'),
  ('language', 'zh-CN'),
  ('record_enabled', 'true'),
  ('record_preserve_time', '72'),
  ('ping_record_preserve_time', '72'),
  ('record_persist_interval_sec', '120'),
  ('ping_record_persist_interval_sec', '120'),
  ('record_high_watermark_rows', '450000'),
  ('capacity_daily_view_minutes', '60'),
  ('audit_log_preserve_time', '2160'),
  ('live_poll_active_interval_sec', '3'),
  ('live_poll_idle_interval_sec', '120'),
  ('live_poll_active_max_duration_sec', '600'),
  ('notification_method', 'telegram'),
  ('telegram_bot_token', ''),
  ('telegram_chat_id', ''),
  ('enable_ip_change_notification', 'false'),
  ('active_theme', 'default')
on conflict (key) do nothing;

alter table public.clients enable row level security;
alter table public.records enable row level security;
alter table public.gpu_records enable row level security;
alter table public.gpu_snapshots enable row level security;
alter table public.users enable row level security;
alter table public.login_rate_limits enable row level security;
alter table public.settings enable row level security;
alter table public.themes enable row level security;
alter table public.theme_assets enable row level security;
alter table public.ping_tasks enable row level security;
alter table public.ping_records enable row level security;
alter table public.ping_snapshots enable row level security;
alter table public.website_monitors enable row level security;
alter table public.website_checks enable row level security;
alter table public.offline_notifications enable row level security;
alter table public.expiry_notifications enable row level security;
alter table public.load_notifications enable row level security;
alter table public.audit_logs enable row level security;
alter table public.clients force row level security;
alter table public.records force row level security;
alter table public.gpu_records force row level security;
alter table public.gpu_snapshots force row level security;
alter table public.users force row level security;
alter table public.login_rate_limits force row level security;
alter table public.settings force row level security;
alter table public.themes force row level security;
alter table public.theme_assets force row level security;
alter table public.ping_tasks force row level security;
alter table public.ping_records force row level security;
alter table public.ping_snapshots force row level security;
alter table public.website_monitors force row level security;
alter table public.website_checks force row level security;
alter table public.offline_notifications force row level security;
alter table public.expiry_notifications force row level security;
alter table public.load_notifications force row level security;
alter table public.audit_logs force row level security;

do $$
declare
  role_name text;
begin
  revoke all on schema public from public;
  revoke all on all tables in schema public from public;
  revoke all on all sequences in schema public from public;
  revoke all on all functions in schema public from public;
  alter default privileges in schema public revoke all on tables from public;
  alter default privileges in schema public revoke all on sequences from public;
  alter default privileges in schema public revoke all on functions from public;

  foreach role_name in array array['anon', 'authenticated'] loop
    if to_regrole(role_name) is not null then
      execute format('revoke all on schema public from %I', role_name);
      execute format('revoke all on all tables in schema public from %I', role_name);
      execute format('revoke all on all sequences in schema public from %I', role_name);
      execute format('revoke all on all functions in schema public from %I', role_name);
      execute format('alter default privileges in schema public revoke all on tables from %I', role_name);
      execute format('alter default privileges in schema public revoke all on sequences from %I', role_name);
      execute format('alter default privileges in schema public revoke all on functions from %I', role_name);
    end if;
  end loop;
end $$;

comment on table clients is 'CF Monitor internal table. Public access must go through the Worker API.';
comment on table users is 'CF Monitor admin users. Do not expose through Supabase Data API.';
comment on table settings is 'CF Monitor settings and internal health keys. Do not expose through Supabase Data API.';

insert into settings (key, value)
values ('schema_bootstrap_version', 'postgres-2026-06-15-v2')
on conflict (key) do update set value = excluded.value;

commit;
