begin;

set local search_path = public;

create table if not exists website_monitors (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  method text not null default 'GET',
  expected_status_min integer not null default 200,
  expected_status_max integer not null default 399,
  interval_sec integer not null default 120,
  timeout_sec integer not null default 10,
  grace_period_sec integer not null default 180,
  enabled boolean not null default true,
  hidden boolean not null default false,
  sort_order integer not null default 0,
  status text not null default 'pending',
  last_checked_at timestamptz,
  last_success_at timestamptz,
  last_failure_at timestamptz,
  last_status_code integer,
  last_raw_status_code integer,
  last_latency_ms integer,
  last_effective_reason text,
  last_error text,
  down_since timestamptz,
  last_notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint website_monitors_method_check check (method in ('GET', 'HEAD', 'TCP')),
  constraint website_monitors_status_check check (status in ('pending', 'up', 'down', 'paused')),
  constraint website_monitors_expected_status_check check (
    expected_status_min between 100 and 599
    and expected_status_max between 100 and 599
    and expected_status_min <= expected_status_max
  ),
  constraint website_monitors_interval_check check (interval_sec between 60 and 86400),
  constraint website_monitors_timeout_check check (timeout_sec between 1 and 30 and timeout_sec <= interval_sec),
  constraint website_monitors_grace_check check (grace_period_sec between 30 and 86400)
);

create table if not exists website_checks (
  id bigint generated by default as identity primary key,
  monitor_id bigint not null,
  checked_at timestamptz not null,
  ok boolean not null,
  effective_status text not null default 'down',
  effective_reason text,
  status_code integer,
  raw_status_code integer,
  latency_ms integer,
  error text,
  constraint website_checks_monitor_id_fkey foreign key (monitor_id) references website_monitors(id) on delete cascade
);

create index if not exists idx_website_monitors_sort_order on website_monitors(sort_order, id);
create index if not exists idx_website_monitors_due on website_monitors(enabled, last_checked_at, interval_sec);
create index if not exists idx_website_checks_monitor_time on website_checks(monitor_id, checked_at desc);

alter table public.website_monitors enable row level security;
alter table public.website_checks enable row level security;
alter table public.website_monitors force row level security;
alter table public.website_checks force row level security;

grant select, insert, update, delete on public.website_monitors to cf_monitor_app;
grant select, insert, update, delete on public.website_checks to cf_monitor_app;
grant usage on sequence website_monitors_id_seq to cf_monitor_app;
grant usage on sequence website_checks_id_seq to cf_monitor_app;

drop policy if exists cf_monitor_app_all on public.website_monitors;
create policy cf_monitor_app_all on public.website_monitors for all to cf_monitor_app using (true) with check (true);
drop policy if exists cf_monitor_app_all on public.website_checks;
create policy cf_monitor_app_all on public.website_checks for all to cf_monitor_app using (true) with check (true);

insert into settings (key, value)
values ('schema_bootstrap_version', 'postgres-2026-06-15-v16')
on conflict (key) do update set value = excluded.value;

commit;
